services:
  # Backend API Service
  - type: web
    name: auto-maintenance-api
    env: node
    rootDir: api
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: auto-maintenance-db
          property: connectionString
      - key: CLIENT_URL
        fromService:
          name: auto-maintenance-client
          type: web
          property: url

  # Frontend Service
  - type: web
    name: auto-maintenance-client
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_BASE_URL
        fromService:
          name: auto-maintenance-api
          type: web
          property: url

# Database
databases:
  - name: auto-maintenance-db
    plan: starter
    type: postgres
